### ISSUE TITLE
Can you share a sample yaml with spi configured?

### ISSUE THREAD

**Issue by kaansoral** [samoswall/ST7789-TFT-LCD-ESPHome#1]
Hi,

I'd appreciate a sample yaml with spi configured and comments with explanations to where the pins are connected to the LCD board

I'm sure it'll help others too

Thanks for the component,
Kaan

**Comment by kaansoral** [comment]
```
spi:
  clk_pin: GPIO14 #sck
  mosi_pin: GPIO13 #sda

display:
  - platform: st7789v
    reset_pin: GPIO23                    
    dc_pin: GPIO16
    id: my_display
    dimensions: 240x240
    update_interval: 100s
    lambda: |-
      it.print(0, 0, id(font1), "Hello World!");
```

Tried this, and see this:

```
[05:13:18][C][st7789v:123]: SPI ST7789V
[05:13:18][C][st7789v:123]:   Rotations: 0 °
[05:13:18][C][st7789v:123]:   Dimensions: 240px x 240px
[05:13:18][C][st7789v:124]:   DC Pin: GPIO16
[05:13:18][C][st7789v:125]:   Reset Pin: GPIO23
[05:13:18][C][st7789v:128]:   Update Interval: 100.0s
```

Yet nothing on the screen

**Comment by samoswall** [comment]
```
font:
  - file: "fonts/Impact.ttf"
    id: my_font
    size: 20

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: st7789v
    reset_pin: GPIO23
    dc_pin: GPIO16
    id: my_display
    dimensions: 240x240
    update_interval: 0.5s             # not 100s
```
connect 3.3v to the BLK contact
