### ISSUE TITLE
problem when compiling with it.print

### ISSUE THREAD

**Issue by Badkun2002** [samoswall/ST7789-TFT-LCD-ESPHome#2]
Hello, I have a problem when compiling it gives an error, what could be the problem?
ESPHome 2024.12.4
```
error: no matching function for call to 'esphome::display::DisplayBuffer::print(int, int, esphome::font::Font*&, const char [13])'
       it.print(0, 10, id(my_font), "Hello World!");
```

my Yaml config:
```

spi:
  clk_pin: GPIO12
  mosi_pin: GPIO13

# Настройка шрифта
font:
  - file: "Impact.ttf"
    id: my_font
    size: 20

display:
  - platform: st7789v
    dc_pin: GPIO10
    reset_pin: 9
    id: my_display
    dimensions: 240x240
    update_interval: 0.5s

    lambda: |-
      it.print(0, 10, id(my_font), "Hello World!");

```
